version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./pgdata:/var/lib/postgres/data
  web:
    image: new-app
    depends_on:
      - db
    ports: 
      - "4000:4000"


  